version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/app/eventyay/webapp"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/app/eventyay/frontend/schedule"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/app/eventyay/frontend/schedule-editor"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/app/eventyay/frontend/webcheckin-bundler"
    schedule:
      interval: "daily"
