version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/app"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    ignore:
      - dependency-name: "django"
        versions: [">=6.0.0"]
      - dependency-name: "stripe"
        versions: [">=11.4.0"]

  - package-ecosystem: "npm"
    directory: "/app/eventyay/webapp/video"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/app/eventyay/webapp/schedule"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/app/eventyay/webapp/schedule-editor"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/app/eventyay/webapp/webcheckin"
    schedule:
      interval: "daily"
