debug = true

# For development, we just store emails as files.
email_backend = 'eventyay.base.email.FileSavedEmailBackend'

allowed_hosts = ['*']

site_url = 'http://localhost:8000'

redis_url = 'redis://localhost/0'

short_url = 'https://test.eventyay.com'

celery_always_eager = true
