# In testing, we use the in-memory email backend,
# because we do assertions on sent emails and we want to throw away emails after tests.
email_backend = 'django.core.mail.backends.locmem.EmailBackend'

celery_always_eager = true
