debug = true

# For development, we just store emails as files.
email_backend = 'eventyay.base.email.FileSavedEmailBackend'

allowed_hosts = ['*']

site_url = 'https://test.eventyay.com'

redis_url = 'redis://localhost/0'
